language: python
python:
  - '3.6'

env:
  - "DB_PASSWORD=travis"

services:
  - mysql
  - docker

before_install:
  - mysql -e 'CREATE DATABASE codedu;'

install:
  - pip install -r requirements.txt

script:
  - pytest test

before_deploy:
  - sudo cp -f ./config/daemon-test.json /etc/docker/daemon.json
  - sudo systemctl restart docker

deploy:
  provider: script
  script: sudo bash docker-deploy.sh