language: python
python:
- '3.6'
env:
  global:
  - DB_PASSWORD=travis
  # TARGET_IP=
  - secure: qc0dVdDaZbrUGq1zejtU+cIZy74KUsA00W4IQXISg9Jz7CtIJnKbzYPdZ+Av7qT8bG5MirOB5LgIJISyxkwpOvnICSYjPXkSjhhMAyoAbeAy5ByYwIXAi1NAt8+jePEDLPAaiFLlhzLLrS7NiOsGiSb18e8TkL+0NECLy1jDB631oz4VBBbjJzdlYT8Bc9Ut3bJOR7pDPGyxIonviWXzFIYH5wKgvVLzRAPHkI03i+Vbln6XG6l5ikjxA/Q1XlVAqp9EtDfOpYJt3VbjrLb55G9LyYw9nu0M1ygSd3Yk1W19ZzT6Z5OJ+lWLKQcaJZkwPmXmZvZ3i0/bHghIVmEwR1C7CPoEZ4xSf93JFxHzGafYPlhEHiu3EmeEcQDpRw/R67Lot1qcQJI4L5EPVr+StECNbvEzwxEPKA9PsSkxktwGF4Ndrop0YbeFkPfWs9Q9hSUY9qS0mq5A22SmqwZy0JyLje0eYWqWlyh4CYc6Bf8ikHV6wDkEX1eiR/vbYXAGUZ8omWbFsE03KqGVFLV9XqQCMy32OMxwGCSd3gjhDGV8nvTYYGVCndRFlICuFI9TfRbT4n/qMsEOHZnl0/UPKXD8xftYNsxr9pXvlF7ib0tUW3gFVH9HFL8Mncwo2AUeOZZt4JUMGs3e99VAv/hvInpTEQXwB6y0sdmpCjoiEJE=
  - DOCKER_USERNAME=ctmanjak
  # DOCKER_PASSWORD=
  - secure: oaK0iTKBHbzuzLSsgcEHWhPNa6NKOqpdGEnQA50a0msr1piF9DCLoX9KECuoN6vDBhzpoTWwJ0AiER73yChuHrtqobqniecdDqa0RXT6oZGm+c5KedS1mMjkD185uYCCVtnfetxN7tppeYTCpg0BYJdRLCtTnSzldz17GlhwwV5grsbaNcZ5sjcd1pV2b1V2UXkkz791c1fuOuAq4WR5zQdu0TaqAn2+1k9MHbfAqJQh9rCCAowpb5MRYWLMy2A7t1jTU8O6XsHlz4rUzry4bTWlPZ6qiJf4qItsg9q2aO1eUFPnsLcPxbN65lY+F70byUmH7k3RDigtUR9/jHEGP4sUHlQk0I9QKvqVTxwp9sG3YiQusEUOLQn7Pa3r7w3U9G20Js3Bu0DksrNiHTfNb2g4EPNjQYcJmKioe3P4JqOgSeMEpPToMxLvJqLB683wW8yjxk01W/FE/febcM6DQP3vy5CTf3P0APHwIKhNIHElcdmpKWCypQu2FF3OTRIjuefW2RtHOeSmDOVzegMxid6FSMBaHP1bunbdqxPyItg4a1kEnULR6xpgnJVbu9DOpUpyMbndXoVwW6MKSO5SRHWofLt05gIbtRXoFczCSiNlUAVTAY7koL45hSlEefSeFB1MgMT7DwpJK6E4vO3+FTa+I/BtyocZV7PHVZ8vm0I=
services:
- mysql
- docker
before_install:
- mysql -e 'CREATE DATABASE codedu;'
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
# - openssl aes-256-cbc -K $encrypted_*_key -iv $encrypted_*_iv -in secrets.tar.enc -out secrets.tar -d
install:
- pip install -r requirements.txt
script:
- pytest test
after_success:
  - bash image_build.sh
deploy:
  skip_cleanup: true
  provider: script
  script: bash docker-deploy.sh $TARGET_IP
  on:
    branch: master

notifications:
  email:
  - ctmanjak@gmail.com
  slack:
    secure: L06LWIJkZk9v+m3ouCdhF5RbpJtWW/+AtxBKmlxzGo5SUn9XK59YHfb1srN3y/N9mU9cwBXJiCEUovZYWH8s8ArwBJnB7KjLWvTNOy1naGZivH09aMNgzfJQJ8Ujr4qSP3SvB7tdYX5VY0c7zvf1UvB05QyUJ37gdbglcudzdbBfNI3i3mQAyW2Yo1JWyWYPib0jDUzTLRJfGAc7MO1B1yG23yk2f/mHd4O/YyvW+nDKGktRvp2gK+PPh6FhjWfCIts28/ZRLRYnWZ/aoMQvv4NU0yrHPvG14UGStCe8SHjoy61stRwF0712Z1SgNq+ImpWBzm0EY7KAfuOe5krw+0UzUJS5+svAoUuYoeWCntBYz+8ia1VpQ6BUAlMVA7qIwdR382Tk4tO0RXYsSOXScOEMnHm52lkEl79r6jOR0mo9FlK9iRHmb8SE5f+hW5BvxwofgGq5yyErTf+Q1E3XT5gJeJ1uNg7iX2jGJGQiafaV6qVIKQ7pfyRjFyTLGCtPXtGRnK9PRuj6ODFxb1dKGW99Fu9MXSKtcPBJ+q0bmZZJo+Nheu6mfYBqAPsvPa5NqZeu8SetfsBR+j1ZyErz3/zQKcREXHhRu/9jtc9O9nSxc1RhFH3JcShcDbN51OJC6HaJ/yBO9Fs8ZjzE9ataGRd+VAD2lW+/oVDtnuozjeQ=