language: python
python:
- '3.6'
services:
- mysql
- docker
before_install:
- mysql -e 'CREATE DATABASE codedu;'
install:
- pip install -r requirements.txt
script:
- pytest test
deploy:
  provider: script
  script: bash docker-deploy.sh
env:
  global:
  - secure: lrtG90oaUgVWcZTcOImKHRagSV7XytH+GvSnD+sBljvRf3bdyLy5OqrORPrrkZDv56aKZG8TtnRNqmzO5csQl2z1efcZvb5f1PLea97qWy0ZitXFa7Ee9Ti32tSvPcb/ny0FFpLPxK+gz9ENZCvXrb4wQUiYPKL1sHkGJwhR6dq1Gj14yx+vqzT54mg8RqEkHUeifHmGAUO0+07oXyJt/TV+XhEkItindjHQVHYRRGixr7ZMWzsgU3b+pXf77A29cdZc+ppWDfYnjZBaPvnQiM40RJbF51zgp9fUX9lPh3+7CmdTHbqFP6gbtAsuTZ1qamxVy3iB1/his/AXdpMPaY/+9JDnGLPQ7PrLruSRJ747/GUo42lZHE+S8x7M/5v3dcmjhkaRuSIY60JNRlmK1cn4VWIh2X3DwyFr4ZmTU5Xs9PdJMHLVb+5gYQvp94O5zzr9rrTr/ZiirDiqKZ9HuDV3nY4d8wW61hy5S0xl2HkPK1auat24wD2iWMSw4O5bCnaysdQT4FBVuBESiRGePNMXiDahDldbs0CTaC0ZFGBPP0gGncfhQOqqupBiYezKhDhDGP/fLHpJy+JC3YHDKalUmVE02rs7g6mhfKNNJS+yrIB20r86pkDR6QfC2zFJrniZsOUbkvOXZ+zSfHvRMDzS/zO3YRboiTv/8saAAC0=
