language: python
python:
- '3.6'
services:
- mysql
- docker
before_install:
- mysql -e 'CREATE DATABASE codedu;'
install:
- pip install -r requirements.txt
script:
- pytest test
deploy:
  provider: script
  script: bash docker-deploy.sh
env:
  global:
  - secure: tRYCZlZVX3ns4wahFRp+CZ2gXyuFQXjOHBTGs37+p3mLKxNIPRtk/8ltmuxtac+LVlGR3qsjFxCPStAQ2DDgPKIOgC6ozSpUQ8yXdQVC6LcaivY/p9droqYyZ69KN6c6WLZiA5Ko3+WSECCeGXrc53vhn92gl5fAqJbEPRHxKbl4OsO4VwOFZk0V5TCGQYhi1ygOI+uHzqOjHMVmC3GGHil8pni5+E79Oo2GHcg5cTPeubuDVh/9e5k/9vXPYvsOAIV5kluOcMxcJ4cV50lzu3NORiJSefWey0VGrC/iLP8diUQhkgXi5p1uJQL2Lcy94PTiBzIvOlwJvjRxmlaQS7uC7BxzsUb/vnt02UBR2iPd1kYIEAE95voQcagfF0RekL2tPhFjr1YdHnLuHnkW1M9C8FpJovgjWbK9mVKoMljbDK2koq/43tPWtb6h1LIRbUoxSLy7R+ns/C7aTB1ENlr0vVGyl4nBIJWxIweaRnDGJsCZ9e5HaMZ9U1L8wsdKZz2XrSfX7HDWS+OdiV40zve6GZ5+Ra9Ve3MhOO6DApkGaNGD4ssNBN07+dNu0ROGXdFofV8fxSaImSpOIugYAmakGMU7gSyw6k8tcEx9ivh6QwdUXIx8KJNdBR16iV38bXxweWBJODN8tXXIq/eCar3iYuEK73ry7oCu3KlIF5Y=
