language: python
python:
  - '3.6'

env:
  - "DB_PASSWORD=travis"

services:
  - mysql
  - docker

before_install:
  - mysql -e 'CREATE DATABASE codedu;'

install:
  - pip install -r requirements.txt

script:
  - pytest test

deploy:
  provider: script
  script: sudo bash docker-deploy.sh