language: python
python:
  - '3.6'

env:
  - "DB_PASSWORD=travis"

services:
  - mysql
  - docker

before_install:
  - sudo rm -f /etc/docker/daemon.json
  - sudo echo '{"registry-mirrors":["https://mirror.gcr.io"],"mtu":1460,"insecure-registries":["15.165.181.246:5000"]}' > /etc/docker/daemon.json
  - mysql -e 'CREATE DATABASE codedu;'

install:
  - pip install -r requirements.txt

script:
  - pytest test

before_deploy:
  - sudo systemctl restart docker

deploy:
  provider: script
  script: sudo bash docker-deploy.sh