language: python

python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies

services:
  - docker
  
before_install:
  - docker-compose up --force-recreate -d
  - docker-compose exec server /bin/sh -c "pytest /codedu/test"

# install:
#   - pip install -r requirements.txt
# command to run tests
script:
  - pytest test