language: python
python:
  - '3.6'

env:
  - "DB_PASSWORD=travis"
  - secure: qc0dVdDaZbrUGq1zejtU+cIZy74KUsA00W4IQXISg9Jz7CtIJnKbzYPdZ+Av7qT8bG5MirOB5LgIJISyxkwpOvnICSYjPXkSjhhMAyoAbeAy5ByYwIXAi1NAt8+jePEDLPAaiFLlhzLLrS7NiOsGiSb18e8TkL+0NECLy1jDB631oz4VBBbjJzdlYT8Bc9Ut3bJOR7pDPGyxIonviWXzFIYH5wKgvVLzRAPHkI03i+Vbln6XG6l5ikjxA/Q1XlVAqp9EtDfOpYJt3VbjrLb55G9LyYw9nu0M1ygSd3Yk1W19ZzT6Z5OJ+lWLKQcaJZkwPmXmZvZ3i0/bHghIVmEwR1C7CPoEZ4xSf93JFxHzGafYPlhEHiu3EmeEcQDpRw/R67Lot1qcQJI4L5EPVr+StECNbvEzwxEPKA9PsSkxktwGF4Ndrop0YbeFkPfWs9Q9hSUY9qS0mq5A22SmqwZy0JyLje0eYWqWlyh4CYc6Bf8ikHV6wDkEX1eiR/vbYXAGUZ8omWbFsE03KqGVFLV9XqQCMy32OMxwGCSd3gjhDGV8nvTYYGVCndRFlICuFI9TfRbT4n/qMsEOHZnl0/UPKXD8xftYNsxr9pXvlF7ib0tUW3gFVH9HFL8Mncwo2AUeOZZt4JUMGs3e99VAv/hvInpTEQXwB6y0sdmpCjoiEJE=

services:
  - mysql
  - docker

before_install:
  - mysql -e 'CREATE DATABASE codedu;'

install:
  - pip install -r requirements.txt

script:
  - pytest test

before_deploy:
  - sudo cp -f ./config/daemon-test.json /etc/docker/daemon.json
  - sudo systemctl restart docker

deploy:
  provider: script
  script: sudo bash docker-deploy.sh $TARGET_IP