version: '3'
volumes:
  codedu_db: {}
  
services:
  mariadb:
    image: mariadb
    volumes:
      - codedu_db:/var/lib/mysql
      - ./config/mariadb-default.cnf:/etc/mysql/mariadb.conf.d/default.cnf
    environment:
      - MYSQL_DATABASE=codedu
      - MYSQL_ROOT_PASSWORD=root
    logging:
      driver: none

  falcon:
    image: 15.165.181.246:5000/codedu_server:falcon
    build:
      context: .
      dockerfile: ./Dockerfile-falcon
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
        max_failure_ratio: 3
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first
        max_failure_ratio: 3
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: codedu
      DB_USER: root
      DB_PASSWORD: root
      SECRET_KEY: codedu
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PYTHONUNBUFFERED:
    command: ["uvicorn", "look.app:socket", "--host", "0"]

  nginx:
    image: nginx
    volumes:
      - ./config/nginx-default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - falcon