version: '3.7'
volumes:
  codedu_db: {}
  
services:
  mariadb:
    image: mariadb
    volumes:
      - codedu_db:/var/lib/mysql
    configs:
      - source: mariadb_conf
        target: /etc/mysql/mariadb.conf.d/default.cnf
    environment:
      - MYSQL_DATABASE=codedu
      - MYSQL_ROOT_PASSWORD=root

  falcon:
    image: ctmanjak/codedu_falcon:latest
    build:
      context: ..
      dockerfile: ./Dockerfile-falcon
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
        order: stop-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 20s
        order: stop-first
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: codedu
      DB_USER: root
      DB_PASSWORD: root
      SECRET_KEY: codedu
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PYTHONUNBUFFERED:
    command: ["uvicorn", "look.app:socket", "--host", "0"]

  nginx:
    image: nginx
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - falcon

configs:
  mariadb_conf:
    name: mariadb_conf-${MARIADB_CONF_VER}
    file: ../config/mariadb-default.cnf
  nginx_conf:
    name: nginx_conf-${NGINX_CONF_VER}
    file: ../config/nginx-default.conf