version: '3.7'
volumes:
  codedu_db:
  codedu_image:
  
services:
  mariadb:
    image: mariadb
    volumes:
      - codedu_db:/var/lib/mysql
    configs:
      - source: mariadb_conf
        target: /etc/mysql/mariadb.conf.d/default.cnf
    environment:
      - MYSQL_DATABASE=codedu
      - MYSQL_ROOT_PASSWORD=root
    deploy:
      placement:
        constraints:
          - "node.role==manager"
  falcon:
    image: ctmanjak/codedu_falcon
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-falcon
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
        order: stop-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 20s
        order: stop-first
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: codedu
      DB_USER: root
      DB_PASSWORD: root
      SECRET_KEY: codedu
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PYTHONUNBUFFERED: 0
    volumes:
      - codedu_image:/codedu/images
    command: ["uvicorn", "look.app:socket", "--host", "0", "--proxy-headers"]

  nginx:
    image: nginx
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    volumes:
      - codedu_image:/codedu/images
    depends_on:
      - falcon

configs:
  mariadb_conf:
    name: mariadb_conf-${MARIADB_CONF_VER}
    file: ../config/mariadb_default.cnf
  nginx_conf:
    name: nginx_conf-${NGINX_CONF_VER}
    file: ../config/nginx_default.conf