version: '3.4'
volumes:
  codedu_db-dev: {}
  
services:
  mariadb:
    image: mariadb
    volumes:
      - codedu_db-dev:/var/lib/mysql
      - ../config/mariadb_default.cnf:/etc/mysql/mariadb.conf.d/default.cnf
    environment:
      - MYSQL_DATABASE=codedu
      - MYSQL_ROOT_PASSWORD=root

  falcon:
    image: codedu_falcon:dev
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-dev
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: codedu
      DB_USER: root
      DB_PASSWORD: root
      SECRET_KEY: codedu
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PYTHONUNBUFFERED: 0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://falcon:8000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    command: ["uvicorn", "look.app:socket", "--reload", "--host", "0"]
    volumes:
      - ../:/codedu/

  nginx:
    image: nginx
    volumes:
      - ../config/nginx_default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - falcon